---
name: Deploy Surreality Client

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Surreality on GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          cd client
          npm ci

      - name: Build Client
        run: |
          cd client
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client/dist
