---
name: Deploy Surreality Client

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Surreality on GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Chande Directory
        run: cd client

      - name: Build Client
        run: npm ci && npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
