---
name: Publish Documentation

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Publish Documentation
        run: |
          echo "Publishing Documentation"
          echo "Documentation ${{ github.ref_name }} published"
