---
name: Publish Package on GitHub Container Registry and Docker Hub

on:
  push:
    tags:
      - 'package-v*'

jobs:
  package:
    name: Publish Package on Registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    env:
      DOCKER_IMAGE: ${{ github.repository }}-api

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}
            ghcr.io/${{ github.repository }}

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: ./api
          file: ./api/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
