---
name: Publish Package

on:
  push:
    tags:
      - 'package-v*'

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Publish Package
        run: |
          echo "Publishing Package"
          echo "Package ${{ github.ref_name }} published"
